# These are supported funding model platforms
# Uncomment and add your username to enable sponsorship

# github: [your-github-username]
# patreon: your-patreon-username
# open_collective: your-open-collective-username
# ko_fi: your-ko-fi-username
# tidelift: npm/package-name
# community_bridge: project-name
# liberapay: your-liberapay-username
# issuehunt: your-issuehunt-username
# lfx_crowdfunding: project-name
# polar: your-polar-username

# Custom sponsorship URL (can be any URL)
# custom: ['https://your-custom-sponsorship-link']
