import js from '@eslint/js';

export default [
  js.configs.recommended,
  {
    files: [
      'js/config.js',
      'js/main.js',
      'js/page.js',
      'js/pageData.js',
      'js/images.js',
      'js/diary.js',
      'js/ogod.js',
      'js/analytics.js',
      'js/audioPlayer.js',
      'js/audioAnalyzerBridge.js',
      'js/uiSounds.js',
      'js/videoPlayer.js',
      'js/nameSearch.js',
      'js/namingAPI.js',
      'js/namingStrategies.js',
      'js/loophole.js',
      'js/sketch.js',
      'js/3d/**/*.js',
    ],
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: 'script',
      globals: {
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        navigator: 'readonly',
        $: 'readonly',
        jQuery: 'readonly',
        ga: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        setTimeout: 'readonly',
        requestAnimationFrame: 'readonly',
        fetch: 'readonly',
        btoa: 'readonly',
        THREE: 'readonly',
        Tone: 'readonly',
        Howler: 'readonly',
        createjs: 'readonly',
        ETCETER4_CONFIG: 'writable',
        audioBridge: 'writable',
        AudioAnalyzerBridge: 'writable',
        UISounds: 'writable',
        SceneManager: 'writable',
        EnvironmentData: 'writable',
        EnvironmentBase: 'writable',
        LandingCompositor: 'writable',
        OGODSceneManager: 'writable',
        OGODAudioEngine: 'writable',
        FirstPersonController: 'writable',
        GradientFogEnvironment: 'writable',
        StripeBarEnvironment: 'writable',
        BokehGridEnvironment: 'writable',
        HighContrastEnvironment: 'writable',
        LayeredColorsEnvironment: 'writable',
        GlitchDigitalEnvironment: 'writable',
        NoiseShaders: 'writable',
        createOGODExperience: 'writable',
        SettingsPanel: 'writable',
        StemMixer: 'writable',
        PresetSelector: 'writable',
        SessionManager: 'writable',
      },
    },
    rules: {
      'no-unused-vars': 'warn',
      'no-undef': 'off', // Disabled because code uses global scope for cross-file communication
      'prefer-const': 'error',
      'no-var': 'error',
      'no-console': 'warn',
      'prefer-template': 'warn',
      'prefer-arrow-callback': 'warn',
      'object-shorthand': 'warn',
      'no-throw-literal': 'error',
      eqeqeq: ['error', 'always'],
      curly: ['error', 'all'],
    },
  },
  {
    // Special config for files that define global classes/objects
    files: ['js/3d/**/*.js', 'js/config.js'],
    rules: {
      // Allow class/const definitions that are assigned to window or global scope
      'no-redeclare': 'off',
    },
  },
  {
    ignores: [
      'node_modules/**',
      'css/vendor/**',
      'js/vendor/**',
      'js/sketches/**',
      'dependencies/**',
      'js/legacy.js',
      'js/test/**',
    ],
  },
];
