import js from '@eslint/js';

export default [
  js.configs.recommended,
  {
    files: [
      'js/config.js',
      'js/main.js',
      'js/page.js',
      'js/pageData.js',
      'js/images.js',
      'js/diary.js',
      'js/ogod.js',
      'js/analytics.js',
      'js/audioPlayer.js',
      'js/audioAnalyzerBridge.js',
      'js/uiSounds.js',
      'js/videoPlayer.js',
      'js/nameSearch.js',
      'js/namingAPI.js',
      'js/namingStrategies.js',
      'js/loophole.js',
      'js/sketch.js',
      'js/3d/**/*.js',
      'js/ogod/**/*.js',
      'js/living-pantheon/**/*.js',
      'js/media/**/*.js',
      'js/discovery/**/*.js',
      'js/ergasterion/**/*.js',
      'js/generative/**/*.js',
    ],
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: 'script',
      globals: {
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        navigator: 'readonly',
        $: 'readonly',
        jQuery: 'readonly',
        ga: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        setTimeout: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        clearTimeout: 'readonly',
        localStorage: 'readonly',
        performance: 'readonly',
        Image: 'readonly',
        AudioContext: 'readonly',
        fetch: 'readonly',
        btoa: 'readonly',
        THREE: 'readonly',
        Tone: 'readonly',
        Howler: 'readonly',
        Hls: 'readonly',
        videojs: 'readonly',
        createjs: 'readonly',
        ETCETER4_CONFIG: 'writable',
        audioBridge: 'writable',
        AudioAnalyzerBridge: 'writable',
        UISounds: 'writable',
        SceneManager: 'writable',
        EnvironmentData: 'writable',
        EnvironmentBase: 'writable',
        LandingCompositor: 'writable',
        OGODSceneManager: 'writable',
        OGODAudioEngine: 'writable',
        FirstPersonController: 'writable',
        GradientFogEnvironment: 'writable',
        StripeBarEnvironment: 'writable',
        BokehGridEnvironment: 'writable',
        HighContrastEnvironment: 'writable',
        LayeredColorsEnvironment: 'writable',
        GlitchDigitalEnvironment: 'writable',
        NoiseShaders: 'writable',
        OGODAnimationEngine: 'writable',
        OGODImageLoader: 'writable',
        OGODFrameSequencer: 'writable',
        OGODCanvasRenderer: 'writable',
        OGODWebGLRenderer: 'writable',
        OGODGenerativeRenderer: 'writable',
        OGODTKOLRenderer: 'writable',
        OGODAudioAdapter: 'writable',
        OGODExportPipeline: 'writable',
        createOGODExperience: 'writable',
        SettingsPanel: 'writable',
        StemMixer: 'writable',
        PresetSelector: 'writable',
        SessionManager: 'writable',
        LivingPantheonCore: 'writable',
        GlobalGlitchSystem: 'writable',
        AmbientSoundLayer: 'writable',
        EnhancedAudioPlayer: 'writable',
        WaveformVisualizer: 'writable',
        LyricsSync: 'writable',
        EnhancedVideoPlayer: 'writable',
        HLSLoader: 'writable',
        MediaURLResolver: 'writable',
        ContentRegistry: 'writable',
        SearchEngine: 'writable',
        FilterSystem: 'writable',
        RelatedWorksEngine: 'writable',
        ShareLinks: 'writable',
        DiscoveryController: 'writable',
        MorphingImageSystem: 'writable',
        AnimatedContentSystem: 'writable',
        LabyrinthGenerator: 'writable',
        GlitchTunnelSystem: 'writable',
        PixelSortUtils: 'writable',
        ExhibitPortal: 'writable',
        ExhibitBridge: 'writable',
        PlaylistManager: 'writable',
        PinakothekeGenerator: 'writable',
        KhronosTimeline: 'writable',
        BibliothekePoetry: 'writable',
        OikosJournal: 'writable',
        SymposionDialogues: 'writable',
        TheatronVisuals: 'writable',
        crypto: 'readonly',
        IntersectionObserver: 'readonly',
        MiniSearch: 'readonly',
        akademiaConfig: 'readonly',
        bibliothekeConfig: 'readonly',
        PINAKOTHEKE_CONFIG: 'readonly',
        ODEION_CONFIG: 'readonly',
        AGORA_CONFIG: 'readonly',
        SYMPOSION_CONFIG: 'readonly',
        OIKOS_CONFIG: 'readonly',
        THEATRON_CONFIG: 'readonly',
        ERGASTERION_CONFIG: 'readonly',
        KHRONOS_CONFIG: 'readonly',
        URLSearchParams: 'readonly',
        CustomEvent: 'readonly',
        sessionStorage: 'readonly',
        showNewSection: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
      'no-undef': 'off', // Disabled because code uses global scope for cross-file communication
      'prefer-const': 'error',
      'no-var': 'error',
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      'prefer-template': 'warn',
      'prefer-arrow-callback': 'warn',
      'object-shorthand': 'warn',
      'no-throw-literal': 'error',
      eqeqeq: ['error', 'always'],
      curly: ['error', 'all'],
    },
  },
  {
    // Special config for files that define global classes/objects
    files: [
      'js/3d/**/*.js',
      'js/ogod/**/*.js',
      'js/config.js',
      'js/page.js',
      'js/pageData.js',
      'js/living-pantheon/**/*.js',
      'js/media/**/*.js',
      'js/discovery/**/*.js',
      'js/ergasterion/**/*.js',
      'js/generative/**/*.js',
      'js/audioAnalyzerBridge.js',
      'js/uiSounds.js',
    ],
    rules: {
      // Allow class/const definitions that are assigned to window or global scope
      'no-redeclare': 'off',
    },
  },
  {
    ignores: [
      'node_modules/**',
      'css/vendor/**',
      'js/vendor/**',
      'js/sketches/**',
      'dependencies/**',
      'js/test/**',
    ],
  },
];
