export const exhibits = [
  'audio-orb',
  'gemini-ink-studio',
  'p5js-playground',
  'synthwave-space',
];

// These are public surfaces, not a copy of the repository. New roots need review.
export const rootFiles = new Set([
  'index.html',
  '404.html',
  'OGOD.html',
  'analog.html',
  'loophole.html',
  'naming-demo.html',
  'offline.html',
  'ogod-3d.html',
  'sitemap.html',
  'manifest.json',
  'sw.js',
  'CNAME',
  'robots.txt',
  'sitemap.xml',
  'LICENSE',
  'css/vendor/tachyons/license',
  'dependencies/images/111119-social-icons-rounded/license.pdf',
  'img/icons/iconattribution.txt',
  'dependencies/vendor/howler/LICENSE.md',
]);
export const publicRoots = new Set([
  'agora',
  'akademia',
  'audio',
  'bibliotheke',
  'chambers',
  'css',
  'dependencies',
  'ergasterion',
  'fonts',
  'html',
  'img',
  'js',
  'json',
  'khronos',
  'labyrinth',
  'odeion',
  'ogod',
  'oikos',
  'pinakotheke',
  'symposion',
  'theatron',
  'video',
]);
export const publicExtensions = new Set([
  '.html',
  '.css',
  '.js',
  '.json',
  '.jpg',
  '.jpeg',
  '.png',
  '.gif',
  '.svg',
  '.webp',
  '.ico',
  '.avif',
  '.mp3',
  '.ogg',
  '.wav',
  '.m4a',
  '.mp4',
  '.webm',
  '.woff',
  '.woff2',
  '.ttf',
  '.eot',
  '.otf',
  '.frag',
  '.vert',
  '.lrc',
  '.vtt',
]);
export const exhibitExtensions = new Set([
  ...publicExtensions,
  '.exr',
  '.wasm',
]);

// Runtime-loaded files are not discovered by Vite's entry graph.
export const staticExhibitFiles = {
  'audio-orb': { 'public/piz_compressed.exr': 'piz_compressed.exr' },
  'synthwave-space': {
    'init/gemini2p5.html': 'init/gemini2p5.html',
    'init/gemini3.html': 'init/gemini3.html',
  },
};
